project:
  type: book

book:
  title: "MTH229 with Julia"
  author: "CSI Math department"
  date: now
  search: true
  repo-url: https://github.com/MTH229/mth229.github.io/
  repo-subdir: quarto/
  repo-branch: master
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - part: "MTH229 notes"
      chapters:
        - calculator.qmd
        - functions.qmd
        - graphing.qmd
        - zeros.qmd
        - limits.qmd
        - derivatives.qmd
        - newton.qmd
        - first-second-derivatives.qmd
        - extrema.qmd
        - integration.qmd
    - part: "MTH232 and 233"
      chapters:
        - mth232.qmd
        - mth233.qmd

format:
  html:
    theme: spacelab
    number-depth: 3
    toc-depth: 3
    link-external-newwindow: true
    include-after: <script  src="https://cdn.jsdelivr.net/gh/yasserelsaid/chatbot@v0.1.4/index.min.js"  data-chatbotId="index-pdf-k527qtaap" ></script>

execute:
  error: true
  freeze: false # auto
